runtime: python311

# Environment variables
env_variables:
  FLASK_ENV: production
  PORT: 8080

# Automatic scaling configuration
automatic_scaling:
  min_instances: 0
  max_instances: 10
  target_cpu_utilization: 0.6
  target_throughput_utilization: 0.6

# Health check
readiness_check:
  path: "/"
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2

liveness_check:
  path: "/"
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2

# Resource allocation
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

# Handlers
handlers:
- url: /.*
  script: auto

